services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: madb
      POSTGRES_USER: madb
      POSTGRES_PASSWORD: madb
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: ./api
    env_file: .env
    depends_on: [db, redis]
    ports: ["8080:8080"]
  web:
    build: ./web
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on: [api]
    ports: ["5173:5173"]
volumes:
  db_data:
